name: hellowm
description: A Flutter project to manage washing machine in IITH.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.14
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.9
  google_sign_in: ^6.0.2
  font_awesome_flutter: ^10.4.0
  provider: ^6.0.5
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Images/logo.webp"
  min_sdk_android: 21 

flutter:
  uses-material-design: true

  assets:
    - assets/Images/
    - assets/hostel/
  #   - images/a_dot_ham.jpeg

